num_workers = 0
port = 8080
rpc_node = 'https://dpayd.dpays.io'
admin_role = 'dpay'
[storage]
type = 's3'
[[log]]
level = 'info'
out = 'stdout'
[database]
dialect = 'postgres'
[database.dialectOptions]
ssl = true
